#!/bin/sh
# postinst script for gnome-mplayer
#
# see: dh_installdeb(1)

set -e

. /usr/share/debconf/confmodule



  if [ -L "/usr/lib/i386-linux-gnu/libdconf.so.0" ]; then
     echo "libdconf0 detected."
  else
     ln -sf /usr/lib/i386-linux-gnu/libdconf.so.1 /usr/lib/i386-linux-gnu/libdconf.so.0
  fi

ldconfig

update-menus

 

db_stop;

exit 0
