#!/bin/bash

if [ ! -f "$HOME/.mplayer/input.conf" ]; then
mkdir -p $HOME/.mplayer 2> /dev/null
touch "$HOME/.mplayer/input.conf"
fi

#DIRNAME=$(cd "$(dirname "${0}")";pwd)
LAUNCHDIR="$(dirname "$(readlink -f "$0")")"
export LD_LIBRARY_PATH="$LAUNCHDIR/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
#cd "$LAUNCHDIR/"
export PATH=$LAUNCHDIR/:"${PATH}"
gnome-mplayer "$@"
