#!/bin/bash
SQUASH="$(dirname "$1")/$(basename $2).squashfs-$RANDOM"
mksquashfs "$1" "$SQUASH" -root-owned -noappend
cat runtime-new >> "$(dirname "$1")/$(basename $2)"
cat "$SQUASH" >> "$(dirname "$1")/$(basename $2)"
echo
echo "Making $(dirname "$1")/$(basename $2) executable..." 
chmod a+x "$(dirname "$1")/$(basename $2)"
rm -f "$SQUASH"
echo
echo "Done !"